title: Professional Engineers Board (PEB)
url: https://www1.peb.gov.sg
favicon: /images/icon_tab.png
colors:
  primary-color: "#2e509f"
  secondary-color: "#ff0000"
  media-colors:
    - title: media-color-one
      color: "#ff0000"
    - title: media-color-two
      color: "#2e509f"
    - title: media-color-three
      color: "#2e509f"
    - title: media-color-four
      color: "#bd10e0"
    - title: media-color-five
      color: "#9013fe"
description: >-
  The Professional Engineers Board Singapore (PEB) is a statutory board in the
  Ministry of National Development. PEB was established since 1971 under the
  Professional Engineers Act.

  PEB’s Mission is to safeguard life, property, and welfare of the public by setting and maintaining high standards for registering professional engineers, and by regulating and advancing the practice of professional engineering.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1le8zwfdek8v1.amplifyapp.com
prod: https://master.d1le8zwfdek8v1.amplifyapp.com
resources_name: news
shareicon: /images/PEB-logo-cropped.jpg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
